import { projects } from '@/lib/data/projects'
import { caseStudies } from '@/lib/data/case-studies'
import prism from '@/components/ui/QuietPrism.module.css'

export type Example = { label: string; route: string; selector: string; modal?: string }
export type Pattern = {
  id: string; name: string; group: string; description: string
  sources: string[]; anatomy: string[]; behavior: string; responsive: string
  examples: Example[]; retained?: boolean
}

const home = (label: string, selector: string): Example => ({ label, selector, route: '/' })
const index = (label: string, selector: string): Example => ({ label, selector, route: '/case-studies/' })
const modal = (label: string, id: string, selector: string): Example => ({ label, selector, route: '/', modal: id })
const featured = projects.filter(p => p.visible && p.section === 'work' && p.display === 'feature').sort((a,b) => a.order-b.order)
const thumbnails = projects.filter(p => p.visible && p.section === 'work' && p.display === 'thumb')
const workExamples = featured.map(p => home(p.title, `.work-item-${p.id} .featured-work-card`))
const storyExamples = (selector: string) => caseStudies.map(s => ({ label: s.shortTitle, selector, route: `/case-studies/${s.slug}/` }))
const modalExamples = (selector: string) => [...featured, ...thumbnails].map(p => modal(p.title,p.id,selector))
const sharedStyles = ['components/ui/QuietPrism.module.css', 'app/visual-system.css', 'app/site-integration.css']
const modalSource = ['components/ui/CaseStudyModal.tsx', 'lib/data/projects.ts', 'app/site-integration.css']
const cardBehavior = 'Use the example itself: hover, Tab to its control, then Enter or click. Atmospheric artwork accelerates briefly on hover or focus, then slows while held. Release restores its idle pace. The baseline has no dedicated Quiet Prism pressed or disabled variant.'
const cardResponsive = 'The example keeps the real page container and media queries. Fit uses the available width; Tablet is 820 CSS pixels; Phone is 390 CSS pixels. Wider previews scroll horizontally without scaling.'
function pattern(id: string, name: string, group: string, description: string, sources: string[], anatomy: string[], examples: Example[], behavior = cardBehavior, responsive = cardResponsive): Pattern {
  return { id, name, group, description, sources, anatomy, examples, behavior, responsive }
}

export const catalog: Pattern[] = [
  pattern('spotlight-split','Spotlight Split','Cards','The featured project card, with its original artwork and copy. All five project families are shown in their actual page layout.', ['components/ui/WorkCard.tsx','components/ui/FeaturedArtwork.tsx',...sharedStyles], ['FeaturedField + FeaturedAnchor','PrismWave','featured-work-art','featured-work-copy','featured-work-open'], workExamples),
  pattern('process-tile','Process Tile','Cards','Icon-led work cards with project-specific geometry and a lower reading panel.', ['components/sections/FullStackSection.tsx','components/ui/ProjectGeometry.tsx',...sharedStyles], ['thinking-thumb-icon','thinking-media','thinking-icon-anchor','thinking-panel'], thumbnails.filter(p=>!p.thumb).map(p=>home(p.title,`[data-project-id="${p.id}"] .thinking-thumb`))),
  pattern('image-tile','Image Tile','Cards','The photo-led branch of the work-card family. The original image remains behind the copy panel.', ['components/sections/FullStackSection.tsx',...sharedStyles], ['thinking-thumb-photo','thinking-photo-image','thinking-panel'], thumbnails.filter(p=>p.thumb).map(p=>home(p.title,`[data-project-id="${p.id}"] .thinking-thumb`))),
  pattern('role-ledger','Role Ledger','Cards','Employment history with real brand marks, role hierarchy, dates and expandable copy.', ['components/sections/ResumeSection.tsx','components/ui/ExperienceDisclosure.tsx',...sharedStyles], ['resume-experience-card','resume-experience-header','resume-experience-details','resume-disclosure-plus'], [['Health-E Commerce','health'],['Mutual of America','mutual'],['One Park Financial','one-park'],['DentalPlans.com','dentalplans'],['Bluegreen Vacations','bluegreen']].map(([label,tone])=>home(label,`.resume-timeline-entry-${tone} .resume-experience-card`)), 'Click the card or its More control. The native disclosure opens and closes with animated height and opacity. Reduced motion removes that animation. Text selection and nested links do not toggle the card.'),
  pattern('practice-stack','Practice Stack','Cards','The complete mentorship, expertise and tools composition. Its three sections share one outer card.', ['components/sections/ResumeSection.tsx',...sharedStyles], ['resume-prism-practice','resume-practice-column','CornerWaves both'], [home('Complete composition','.resume-prism-practice')], 'This reading panel has no whole-card action. Links, where present, retain their own semantics.'),
  pattern('leadership','Leadership Principles','Cards','Four reading tiles inside About and experience, using the registered scope and outcome wording.', ['components/sections/ResumeSection.tsx',...sharedStyles], ['resume-leadership-grid','li'], [home('Four principles','.resume-leadership-grid')], 'Non-interactive content. These tiles do not open dialogs.'),
  pattern('credential-shard','Credential Shard','Cards','Credentials in the real masonry layout. Each external-link action retains its specific accessible label.', ['components/sections/EducationSection.tsx','app/site-integration.css'], ['education-mosaic','education-card','education-tone-0 through education-tone-4'], Array.from({length:9},(_,i)=>home(`Credential ${i+1}`,`.education-card:nth-child(${i+1})`)), 'Use the external-link control. The card is a reading surface, not a full-card link. The visible View label was removed by B65.', 'The masonry uses one column, two from 600px, and three from 1200px. The real titles determine card heights.'),
  pattern('career-snapshot','Career Snapshot','Cards','The four linked career figures on the case-study index, with their original labels and destinations.', ['components/case-studies/CareerStats.tsx','app/case-studies/dashboard.css','app/site-integration.css'], ['cs-career-grid','cs-stat'], [index('Career figures','.cs-career')]),
  pattern('outcome-feature','Outcome Feature','Cards','The lead outcome card with its original before-and-after launch comparison.', ['components/case-studies/OutcomeDashboard.tsx','components/case-studies/StudyVisual.tsx','app/case-studies/case-studies.css','app/site-integration.css'], ['cs-featured','cs-featured-art','cs-featured-copy','cs-launch-comparison','cs-week-track'], [index('Platform launch comparison','.cs-featured')]),
  pattern('outcome-tile','Outcome Tile','Cards','Qualitative outcomes. These are distinct from the numeric comparison and from the story cards.', ['components/case-studies/OutcomeDashboard.tsx','components/case-studies/StudyIconArt.tsx','app/site-integration.css'], ['cs-outcome-card','cs-icon-copy','cs-outcome-type','cs-outcome-label'], caseStudies.filter(s=>s.slug!=='one-platform-five-properties').map(s=>index(s.shortTitle,`.cs-outcome-card[href="/case-studies/${s.slug}/"]`))),
  pattern('story-slate','Story Slate','Cards','The six story links, using each story’s actual icon artwork, disciplines, summary and Read action.', ['components/case-studies/StudyCollection.tsx','components/case-studies/StudyIconArt.tsx','app/site-integration.css'], ['cs-study-grid','cs-study-card','cs-card-copy','cs-text-link'], caseStudies.map(s=>index(s.shortTitle,`.cs-study-card[href="/case-studies/${s.slug}/"]`))),
  {...pattern('signal-tile','Signal Tile','Retained','BannerCard remains in source. B65 removed its four pathway instances from the homepage. These four tone specimens use documentation props.', ['components/ui/QuietPrism.tsx','components/ui/QuietPrism.module.css'], ['BannerCard','banner','bannerCopy','bannerAction','gold / green / purple / rose'], ['gold','green','purple','rose'].map(tone=>({label:tone,route:'/design-system/retained/',selector:`#${tone}`})), 'The component can render an article or a link depending on its href prop. These retained specimens are articles and have no fabricated action.'),retained:true},
  pattern('prism-field','Prism Field','Foundations','The colored atmospheric field behind each featured project. Each family carries its own artwork and palette.', ['components/ui/FeaturedArtwork.tsx',...sharedStyles], ['FeaturedField','featured-work-card-{project.id}','data-atmosphere'], workExamples, 'Artwork is decorative. Motion is governed by the shared atmospheric controller, visibility and user preference.'),
  pattern('crossing-tide','Crossing Tide','Foundations','The real section-boundary wave. Keep this separate from the raster PrismWave inside featured cards.', ['components/ui/WaveSeparator.tsx','app/site-integration.css'], ['MAIN_WAVE_PATH','work-wave-reverse'], [home('Selected-work boundary','.work-wave-reverse')], 'Decorative section artwork, not an interactive control.'),
  pattern('corner-current','Corner Current','Foundations','Three independently moving layers cropped into a corner. Reading and employment panels also use the mirrored bottom corner.', ['components/ui/QuietPrism.tsx','components/ui/QuietPrism.module.css'], ['CornerWaves','cornerTop','cornerBottom','cornerLayer','data-atmosphere-wave'], [home('Single corner','.education-card'),home('Both corners','.resume-prism-practice')], 'The three CSS layers use 16s, 21s and 25s base durations. Pause motion and operating-system reduced motion stop their movement.'),
  pattern('frost-pane','Frost Pane','Foundations','The translucent reading panel inside the featured card. The preview retains its actual backdrop, filter and surrounding field.', ['components/ui/QuietPrism.tsx',...sharedStyles], ['featured-work-copy','quiet-prism-frost','backdrop-filter'], featured.map(p=>home(p.title,`.work-item-${p.id} .featured-work-copy`)), 'The pane belongs to its parent card and has no separate action.'),
  pattern('inset-light-edge','Inset Light Edge','Foundations','The inset edge shine on an employment card. It is a decorative child, not a second border token.', [...sharedStyles,'components/ui/ExperienceDisclosure.tsx'], ['edgeShine','::before / ::after','--atmosphere-shine','--atmosphere-shift'], [home('Employment card','.resume-experience-card')], 'The atmospheric controller adjusts shine and shift from scroll velocity, hover and focus. Paused and reduced-motion modes suppress that interaction.'),
  pattern('tint-edge','Tint Edge','Foundations','Family-colored edges across featured, credential and story cards. Their selectors differ, so they are shown in context.', sharedStyles.concat('app/case-studies/case-studies.css'), ['featured-work-card','education-card','cs-study-card'], [workExamples[0],home('Credential','.education-card'),index('Story','.cs-study-card')]),
  pattern('ribbon-rule','Ribbon Rule','Foundations','The site’s centered divider and its heading treatment, reused inside content and dialogs.', ['app/globals.css','app/site-integration.css','components/ui/SectionHeader.tsx'], ['solid-center','rule-heading'], [home('Section heading','#work .solid-center'),modal('Dialog heading','webmd','.modal-study-content .solid-center')], 'Decorative separation. It carries no action or focus state.'),
  pattern('quiet-label','Quiet Label','Foundations','Eyebrows and metadata retain their source hierarchy. Ordinary words use sentence or title case.', ['components/ui/QuietPrism.module.css','app/case-studies/case-studies.css','app/site-integration.css'], ['eyebrow','cs-eyebrow','thinking-eyebrow'], [home('Featured eyebrow',`.work-item-webmd .${prism.eyebrow}`),index('Case-study eyebrow','.cs-eyebrow')], 'Reading text, not a button or selectable chip.'),
  pattern('discipline-pebble','Discipline Pebble','Foundations','Discipline metadata on featured and story cards, plus the distinct contribution badges in dialogs.', ['components/ui/WorkCard.tsx','components/ui/CaseStudyModal.tsx','app/site-integration.css'], ['featured-work-copy [aria-label="Disciplines"]','cs-badges','modal-badges','badge-work'], [home('Featured disciplines','.featured-work-copy [aria-label="Disciplines"]'),index('Story disciplines','.cs-study-card .cs-badges'),modal('Contributions','webmd','.modal-badges')], 'Badges label content. They do not filter; the Filter Rail is the separate interactive pattern.'),
  pattern('context-medallion','Context Medallion','Foundations','A decorative context icon inside the featured card. The large brand anchor is a different element.', ['components/ui/WorkCard.tsx','components/ui/QuietPrism.module.css'], ['featuredContextIcon','featured-work-anchor'], [home('WebMD context icon',`.work-item-webmd .${prism.featuredContextIcon}`)], 'The icon is hidden from assistive technology. The enclosing card control provides its accessible name.'),
  pattern('trail-arrow','Trail Arrow','Foundations','The existing outlined arrow travels with View and Read actions. The two areas use their own arrow component.', ['components/ui/QuietPrism.tsx','components/case-studies/Arrow.tsx','components/ui/QuietPrism.module.css','app/case-studies/case-studies.css'], ['DirectionalArrow','directionalArrow','cs-arrow','cs-text-link'], [home('View action',`.work-item-webmd .${prism.featuredFooter}`),index('Read action','.cs-study-card .cs-text-link')], 'Hover the parent card to see its authored arrow travel. The arrow is decorative; activate the parent control.'),
  pattern('project-artwork','Project Artwork','Foundations','Original featured identities, thumbnail geometry and dedicated-story illustrations. No substitute artwork is drawn by this reference.', ['components/ui/FeaturedArtwork.tsx','components/ui/ProjectGeometry.tsx','components/case-studies/StudyIconArt.tsx','components/case-studies/StudyVisual.tsx'], ['FeaturedAnchor','FeaturedField','ProjectGeometry','StudyIconArt','StudyVisual'], [...workExamples,index('Story icon artwork','.cs-study-card'),...storyExamples('.cs-detail-cover')], 'Artwork is decorative where the adjacent text already supplies its meaning. Explanatory reconstructions retain their source caption.'),
  pattern('brand-palette','Brand Palette','Foundations','Live computed token values are read from the source document. Brand, Quiet Prism and case-study tokens are distinct namespaces.', ['app/globals.css','components/ui/QuietPrism.module.css','app/case-studies/case-studies.css'], ['--color-prime / second / third / fourth / fifth / pop','--prism-*','--cs-*'], [workExamples[0],index('Case-study tokens','.cs-site')], 'Color names describe source tokens, not new semantic states.'),
  pattern('type-scale','Type Scale','Foundations','Typography is read from the rendered element, including its actual font stack, size, weight and line height.', ['app/globals.css','app/site-integration.css','app/case-studies/case-studies.css'], ['font-family','font-size','font-weight','line-height','letter-spacing'], [home('Featured heading','.work-item-webmd .featured-work-copy h3'),home('Featured body','.work-item-webmd .featured-work-copy p'),index('Index heading','.cs-index-hero h1'),...storyExamples('.cs-detail-deck')], 'Typography depends on the page context and viewport. The computed values below update when the example loads or resizes.'),
  pattern('reading-sheet','Reading Sheet','Dialogs','The actual case-study dialog with its original hero, close actions and independently scrolling body.', modalSource, ['modal-backdrop','modal','modal-content','modal-header','modal-body','modal-footer','modal-sheet-grabber'], modalExamples('.modal-content'), 'The live example opens the real card trigger. Escape or Close dismisses it; focus returns to that trigger. Tab stays within the dialog. Reset example reopens it.', 'On small screens the dialog becomes a sheet with a drag handle and a footer allowance for the site navigation. Desktop uses the original fullscreen dialog container.'),
  pattern('section-plaque','Section Plaque','Dialogs','An icon and heading above a content section, including the source’s divider.', modalSource, ['modal-section-heading','rule-heading'], [modal('DentalPlans.com','dentalplans','.modal-section-heading'),modal('Reveal','reveal','.modal-section-heading'),modal('Call-center states','call-center-ux','.modal-section-heading')], 'A section heading, not a button.'),
  pattern('evidence-cluster','Evidence Cluster','Dialogs','Grouped informational cards used for concepts and supporting narrative.', modalSource, ['modal-hero-cards','modal-info-card-grid','modal-info-card'], [modal('Reveal concepts','reveal','.modal-info-card-grid'),modal('Wrong campaign','wrong','.modal-info-card-grid')], 'Reading cards with no whole-card action.'),
  pattern('metric-lens','Metric Lens','Dialogs','Measured results retain their value, direction and full label from project data.', modalSource, ['modal-metric-grid','modal-metric-card','result','result-label'], [modal('DentalPlans.com','dentalplans','.modal-metric-grid')], 'Non-interactive figures. The source label is part of the value’s meaning.'),
  pattern('value-sheet','Value Sheet','Dialogs','The value-created list paired with a metric grid.', modalSource, ['modal-value-card','fa-ul'], [modal('DentalPlans.com','dentalplans','.modal-value-card')], 'A reading panel. Its list marks are decorative.'),
  pattern('data-bay','Data Bay','Dialogs','The complete result composition containing its heading, metric cards and value-created list.', modalSource, ['modal-data-panel','modal-data-grid','modal-metric-grid','modal-value-card'], [modal('DentalPlans.com','dentalplans','.modal-data-panel')], 'This groups evidence; it does not add a chart interaction.'),
  pattern('image-frame','Image Frame','Dialogs','Real study images with loading, loaded and error treatments. The reference does not fabricate a network failure.', modalSource, ['ModalStudyImage','modal-image-frame','data-load-state','modal-image-error'], [modal('WebMD','webmd','.modal-study-content .modal-image-frame'),modal('Personas','personas','.modal-image-frame')], 'Images begin loading and become loaded or error. A failed image exposes Retry. Error injection is a test procedure, not a shipped appearance switch.'),
  {...pattern('animated-image','Animated Image','Retained','AnimatedStudyImage remains in source, but no active project reaches its GIF branch in this baseline. This retained specimen uses the existing marketing-automation image.', ['components/ui/AnimatedStudyImage.tsx',...modalSource], ['modal-animated-image','data-frozen','canvas'], [{label:'Marketing automation GIF',route:'/design-system/retained/',selector:'#animated-image'}], 'Pause motion or request reduced motion to display a captured still. The original image remains the source.'),retained:true},
  pattern('supporting-diagram','Supporting Diagram','Dialogs','The production hub and flow illustrations used to explain project structure.', ['components/ui/StudySupportingArt.tsx',...modalSource], ['study-supporting-art','data-supporting-art'], [modal('Dental platform','dentalplans','[data-supporting-art="dental-platform"]'),modal('Hydra','hydra','[data-supporting-art="hydra"]'),modal('Call-center flow','call-center-ux','.study-supporting-art')], 'The diagram’s accessible description remains attached to the source illustration.'),
  pattern('system-diagram','System Diagram','Dialogs','The original progress-band diagrams, including nested brand-theme cells and the flat Hydra variant.', modalSource, ['ProgressDiagram','ProgressCell','progress','progress-bar','progress-bar-striped'], [modal('DentalPlans.com','dentalplans','.modal-study-content .progress'),modal('Hydra','hydra','.modal-study-content .progress')], 'These are explanatory diagrams, not upload progress or loading indicators. Animated stripes honor motion preference.'),
  pattern('icon-grid','Icon Grid','Dialogs','The nomenclature cards and workshop portraits are distinct branches of the same typed media block.', modalSource, ['icon-grid','modal-icon-grid','card-body','row-cols-*'], [modal('Hydra nomenclature','hydra','.modal-icon-grid'),modal('Workshop portraits','workshops','.modal-icon-grid')], 'Reading content. The workshop variant uses actual circular photos without the card wrapper.'),
  pattern('split-narrative','Split Narrative','Dialogs','A responsive media-and-prose row. The content model retains span, order and breakpoint settings for each instance.', modalSource, ['split-row','SplitRow','left / right','reverse','breakpoint'], [modal('Hydra','hydra','.modal-study-content')], 'The example opens the containing content so the relationship to neighboring sections remains visible.'),
  pattern('reference-fold','Reference Fold','Dialogs','Native disclosure for supporting reference content in the dialog.', modalSource, ['modal-reference','details','summary'], [modal('Roadmap structure','roadmap','.modal-reference')], 'Activate the summary with click, Enter or Space to reveal its reference material.'),
  pattern('numbered-list','Numbered List','Dialogs','The roadmap’s original numbered list, separate from unnumbered concept cards.', modalSource, ['StyledList','list-group-numbered'], [modal('UX roadmap','roadmap','.list-group-numbered')], 'Reading content. Numbering describes order, not a current step.'),
  pattern('content-card','Content Card','Dialogs','The retained header-and-rows card used inside roadmap content.', modalSource, ['CardBlock','card-header','card-body'], [modal('UX roadmap','roadmap','.modal-study-content .card')], 'A content example, not an editable form.'),
  pattern('availability-demo','Availability Demo','Dialogs','The call-center case study’s working state demonstration, with its source options and messaging.', ['components/ui/CallCenterDemo.tsx',...modalSource], ['call-center-states','CallCenterDemo','call-center-demo'], [modal('Call-center availability','call-center-ux','.call-center-demo')], 'Use the controls within the original demonstration. These states belong to that case study, not to Quiet Prism cards.'),
  pattern('story-cover','Story Cover','Reading pages','Each dedicated case-study cover retains its explanatory reconstruction and source caption.', ['app/case-studies/[slug]/page.tsx','components/case-studies/StudyVisual.tsx'], ['cs-detail-cover','cs-figure-caption','StudyVisual'], storyExamples('.cs-detail-cover'), 'Decorative visual plus a visible explanation of its reconstructed nature.'),
  pattern('decision-note','Decision Note','Reading pages','An emphasized decision inside long-form prose. It is not a selectable card.', ['app/case-studies/[slug]/page.tsx','app/case-studies/case-studies.css'], ['cs-story-section','cs-decision-callout'], storyExamples('.cs-decision-callout'), 'Reading content. Story navigation links move between sections.'),
  pattern('proof-grid','Proof Grid','Reading pages','Results and at-a-glance summaries keep their full context on the dedicated story page.', ['app/case-studies/[slug]/page.tsx','app/case-studies/case-studies.css','app/site-integration.css'], ['cs-results-grid','cs-at-glance','cs-role-grid'], [ ...storyExamples('.cs-results-grid'),{label:'At a glance',route:'/case-studies/one-platform-five-properties/',selector:'.cs-at-glance'}], 'Results use definition-list semantics. At-a-glance summaries are reading panels.'),
  pattern('hero-identity','Hero Identity','Navigation & states','The actual name, rotating role sequence and selected-work action from the homepage.', ['components/ui/KineticHeroIdentity.tsx','components/sections/HeroSection.tsx','app/site-integration.css'], ['hero-title','kinetic-stage','kinetic-closing','hero-case-studies-link'], [home('Homepage identity','.hero-title')], 'The visual role sequence is decorative; a static accessible role remains available. Pause and reduced-motion modes use the source fallback.'),
  pattern('page-navigation','Page Navigation','Navigation & states','The homepage section rail and the separate case-study header.', ['components/nav/NavMain.tsx','components/case-studies/StudyShell.tsx','app/site-integration.css'], ['the-menu','cs-header','aria-current'], [home('Homepage section rail','#the-menu'),index('Case-study header','.cs-header')], 'Use the actual links. The homepage rail tracks sections; the dedicated pages use page navigation. External destinations are not opened automatically by this reference.'),
  pattern('filter-rail','Filter Rail','Navigation & states','The case-study filters update both outcomes and story cards with a real selected state.', ['components/case-studies/StudyCollection.tsx','app/case-studies/case-studies.css','app/site-integration.css'], ['cs-browse-sticky','cs-filters','aria-pressed','filtered-outcomes','filtered-stories'], [index('All work and discipline filters','.cs-filters')], 'Click a discipline to filter both collections. Selection is exposed with aria-pressed. The sticky label changes with the reading position.'),
  pattern('story-navigation','Story Navigation','Navigation & states','In-story section links and the next-story card at the end of each reading page.', ['app/case-studies/[slug]/page.tsx','app/case-studies/case-studies.css','app/site-integration.css'], ['cs-story-sidebar','cs-next-study','cs-open-circle'], [ ...storyExamples('.cs-story-sidebar'),{label:'Next story',route:'/case-studies/one-platform-five-properties/',selector:'.cs-next-study'}], 'Section links scroll within the story. The next-story link navigates to another case study.'),
  pattern('focus-halo','Focus Halo','Navigation & states','The baseline’s actual keyboard focus treatment. Later focus refinements in another worktree are not part of this version.', ['app/site-integration.css','components/ui/QuietPrism.module.css','app/case-studies/case-studies.css'], [':focus-visible',':focus-within','outline','box-shadow'], [workExamples[0],home('Employment disclosure','.resume-experience-card'),index('Story link','.cs-study-card')], 'Tab into the live page to inspect real keyboard focus. No pseudo-class is painted by the catalog. The baseline does not define an independent disabled card primitive.'),
  pattern('motion-control','Motion Control','Navigation & states','The source’s page-wide pause control and shared atmospheric behavior.', ['components/ui/MotionControls.tsx','components/ui/AtmosphereController.tsx','components/ui/useAtmosphericMotion.ts'], ['site-motion-control','motion-paused','motion-offscreen','data-atmosphere','prefers-reduced-motion'], [home('Homepage pause control','.site-motion-control'),index('Case-study pause control','.site-motion-control')], 'Use Pause motion inside the example. Offscreen and hidden-document animation pauses automatically. With operating-system reduced motion, this control is hidden and the source fallback is already active.'),
]

export const tokenNames = [
  ...['prime','second','third','fourth','fifth','pop'].flatMap(name => [`--color-${name}`,`--color-${name}-light`,`--color-${name}-dark`]),
  ...['ink','muted','purple','blue','green','gold','rose','card-body','card-action','card-detail','card-arrow','wave-chroma'].map(name=>`--prism-${name}`),
  ...['ink','muted','paper','line','accent','tint'].map(name=>`--cs-${name}`),
]
